name: Concurrency PR Test

on:
  push:
    branches: [ alpha ]

concurrency:
  group: deploy-alpha
  cancel-in-progress: true

jobs:
  build-deploy-alpha:
    name: Sleep 5 minutes
    runs-on: ubuntu-latest
    steps:
      - name: build alpha
        run: |
          echo "build alpha..."
          sleep 2m
          echo "finish build alpha!"

      - name: deploy alpha
        run: |
          echo "deploy alpha..."
          sleep 2m
          echo "finish deploy alpha!"
